onlyBuiltDependencies:
  - argon2
  - better-sqlite3
  - esbuild
  - isolated-vm
  - oracledb
  - sharp
  - sqlite3
  - unrs-resolver
  - vue-demi

overrides:
  axios@<1.12.0: '>=1.12.0'
  vite@>=7.1.0 <=7.1.4: '>=7.1.5'
