onlyBuiltDependencies:
  - argon2
  - better-sqlite3
  - esbuild
  - isolated-vm
  - oracledb
  - sharp
  - sqlite3
  - unrs-resolver
  - vue-demi

overrides:
  '@modelcontextprotocol/sdk@<1.24.0': '>=1.24.0'
  axios@<1.12.0: '>=1.12.0'
  js-yaml@>=4.0.0 <4.1.1: '>=4.1.1'
  nodemailer@<=7.0.10: '>=7.0.11'
  vite@>=7.1.0 <=7.1.4: '>=7.1.5'
