name: CI & Release

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * *'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v4
        with:
          node-version: 22.17.0
      - uses: pnpm/action-setup@v4
        with:
          version: 10.14.0
          run_install: false
      - run: pnpm install
      - name: Start Docker Compose
        run: docker-compose up -d
      - name: Run tests
        run: pnpm test
      - name: Docker logs (on failure)
        if: failure()
        run: docker-compose logs
      - name: Stop Docker Compose
        if: always()
        run: docker-compose down

  update-directus-versions:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Atualiza array de versões do Directus nos testes
        run: node .github/scripts/updateDirectusVersions.js
      - name: Commit changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add src/tests/index.spec.ts
          git commit -m "chore: update directus versions in tests" || echo "No changes to commit"
          git push

  release:
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v4
        with:
          node-version: 22.17.0
      - uses: pnpm/action-setup@v4
        with:
          version: 10.14.0
          run_install: false
      - run: pnpm install
      - name: Release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release --access public
