name: Package Deploy

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']
  workflow_dispatch:

jobs:
  test_deploy:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'pnpm'

      - uses: pnpm/action-setup@v2
        with:
          version: 8.x

      - name: Install pnpm
        run: |
          npm install -g pnpm
          export PATH="$(npm bin -g):$PATH"

      - name: Verify pnpm installation
        run: |
          pnpm --version

      - name: Release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          pnpm install
          npx semantic-release --access public
